### ISSUE TITLE
Triage run on Ubuntu/4.01/x86_64 with depexts

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-repository#1304]
see https://github.com/avsm/opam-bulk-logs for the source. Help with triaging is welcome...
- [x] aacplus cannot run as root
- [ ] Annexlib 0.13.5 down due to missing distfile (godi-backup2 has gone)
- [x] aio 0.0.3 bad depext: `libaio.h: No such file or directory`
- [x] alsa 0.2.1 bad depext: `libasound2 not found`
- [ ] altgr-ergo : unknown, need to rerun with stderr logs
- [x] ao 0.2.0 : `libao not found`
- [ ] ackdo-reloaded: installs into `/usr/bin` (#1311)
- [x] aws : unknown, need to rerun with stderr logs
- [x] baardskeerder : warning as error (Incubaid/baardskeerder#7 and #1479)
- [ ] batsh 0.0.5 : missing lots of packages, ocp-build errors
- [x] biocaml : transitive failure due to missing camlzip zlib.h depext
- [x] bitstring : missing `time` binary
- [x] bjack 0.1.4 : cannot run as root
- [x] cairo : transitive missing depext on lablgtk2
- [x] cryptokit: missing depext on zlib
- [x] ocaml-usb: missing depext on `libusb-1.0-0-dev`
- [x] delimcc has bad checksum due to upstream change (#1474)
- [x] riak-pb needs `protoc` protobuf compiler (#1475)
- [x] ogg missing `ogg.pc` (part of libogg-dev) (#1476)
- [x] libvhd missing `vhd.h` (#1477)
- [x] spotlib_js has warnings-as-errors (#1478)
- [ ] ocaml-zmq got a trunk archive (pdhborges/ocaml-zmq#7)
- [x] geoip missing depext on `libgeoip-dev` (#1482)
- [ ] email_message is missing an archive upstream (reported to @diml)
- [x] dns fails due to cstruct 1.0 incompatibility
- [x] imagemagick had bad depext on ubuntu (#1484)
- [x] libsvm missing depexts (#1484)
- [x] lo missing liblo-dev depext (#1485)
- [x] gammu add depexts (#1486)
