### ISSUE TITLE
OCaml 4.11 release readiness checklist

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam-repository#16539]
This issue tracks the build and readiness information of core platform tools and libraries in preparation for the OCaml 4.11 release. It’s intended as a meta-issue / holding place for TODO lists rather than general discussion (which is welcomed on Discuss or on linked issues).

As member of the OCaml release readiness team I will do my best in order to provide a fix for most of the packages that need one and talk with the maintainers of those packages. 

Packages that are fixed upstream, have a PR ready, or can be used as-is for testing purpose, are in https://github.com/kit-ty-kate/opam-alpha-repository

**Platform tools**:
* [x] opam
* [x] dune
* [x] merlin
* [ ] lsp-server / vscode-plugin
* [x] odoc
* [x] ocamlformat
* [x] ocp-indent

**Ecosystem**:
* [x] ocamlfind
* [x] ocamlbuild
* [x] ppxlib
* [x] ocaml-migrate-parsetree
* [x] mdx (fixed in https://github.com/realworldocaml/mdx/pull/261)
* [x] utop
* [x] dune-release
* [x] opam-publish

**Infrastructure**:
* [ ] ocaml.org
* [x] docker base containers
* [x] ocaml-ci (fixed in https://github.com/ocurrent/ocaml-ci/pull/195)
* [x] datakit-ci

A few issues are to be fixed in the compiler first before the release:
* [x] https://github.com/ocaml/ocaml/issues/9603

**Comment by anmonteiro** [comment]
I've done some early work in [merlin-extend](https://github.com/let-def/merlin-extend/pull/13) and [reason](https://github.com/facebook/reason/pull/2582) that adds 4.11 support too.

**Comment by kit-ty-kate** [comment]
@anmonteiro thanks a lot!! I've added the two(+rtop) packages to opam-alpha-repository, it will be checked all the dependency tree overnight.

**Comment by XVilka** [comment]
Shouldn't [ppx_tools](https://github.com/ocaml-ppx/ppx_tools/pull/82) and `ppx_deriving` (which is already was ported) be in that list too?

**Comment by emillon** [comment]
ocamlformat builds on 4.11+alpha3 since ocaml-ppx/ocamlformat#1392 (though I haven't bumped the dependency); I'll continue working on ocaml-ppx/ocamlformat#1387 (thanks for this!) to bump the OMP version, and it'll need more work to support new language features (quoted extensions and class type paths in #-types). So, depends on what you mean by 4.11 support :)

**Comment by emillon** [comment]
I created a milestone for 4.11 support in ocamlformat: https://github.com/ocaml-ppx/ocamlformat/milestone/10

**Comment by avsm** [comment]
mdx.1.7.0 released with 4.11 support, and ocaml-ci added support for it as well in https://github.com/ocurrent/ocaml-ci/pull/219

**Comment by XVilka** [comment]
I think `ocamlformat` can be ticked too, since 0.15.0 release: https://github.com/ocaml-ppx/ocamlformat/releases/tag/0.15.0

**Comment by kit-ty-kate** [comment]
@olafhering ocamlbrowser.4.11.0 has been released a couple of days ago. See: https://github.com/ocaml/opam-repository/pull/17056. Hopefully that should unlock the rest of your build.

**Comment by olafhering** [comment]
Thanks, I have seen it. But I fixed it by just not building the browser.

**Comment by XVilka** [comment]
Should be this closed and unpinned since was finished and last missing piece (LSP) was released too?
