### ISSUE TITLE
policy question: existing packages without checksums

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam-repository#25969]
Dear everyone,

there's a bunch of packages without checksum. I wanted to ensure everyone is on the same page.

My goal is to discuss what to do with the packages that are not checked (i.e. that are available etc. in the opam-repository). I put them into categories and suggested what I'd do. If you agree, let me know - I'm happy to prepare a PR with the suggestions I noted.

## arbitrary packages (my suggestion: mark as `available: false` - each package has a newer version available in opam-repository)
see https://github.com/ocaml/opam-repository/pull/25981
- [x] sedlex.1.99.1 (src: "git+https://github.com/ocaml-community/sedlex.git")
- [x] ppx_tools.0.1 (src: "git+https://github.com/alainfrisch/ppx_tools.git")
- [x] ppx_test.1.5.1 (available: false)
- [x] base.v0.15.1~5.0preview (flags: avoid-version)
- [x] ocamlformat.0.19.0~4.13preview (available: false)
- [x] ppxlib.0.25.0~5.00preview (available: false)
- [x] camltc.0.9.3 (src: "git+https://github.com/toolslive/camltc.git#camltc-0.9.3")
- [x] camltc.0.9.4 (src: "git+https://github.com/toolslive/camltc.git#317e1e4606ce1e86d09b7b83ec2cb1709a81d437")
- [x] camltc.0.9.5 (src: "git+https://github.com/toolslive/camltc.git#camltc-0.9.5")
- [x] camltc.0.9.6 (src: "git+https://github.com/toolslive/camltc.git#camltc-0.9.6")
- [x] quickcheck.0.0.3 (src: "git+https://github.com/avsm/ocaml-quickcheck.git")

## merlin and lsp (inconsistent, there are further `preview` versions with `available: false`), suggestion: mark the remaining two with `available: false`
- [x] ocaml-lsp-server.1.9.0~4.13preview (available: false)
- [x] ocaml-lsp-server.1.9.2~4.14preview (available: false)
- [x] ocaml-lsp-server.1.13.2~5.0preview (flags: avoid-version)
- [x] dot-merlin-reader.4.4~5.0.preview (src: "git+https://github.com/kit-ty-kate/merlin.git#500")
- [x] merlin-lib.4.4~5.0.preview (src: "git+https://github.com/kit-ty-kate/merlin.git#500")
- [x] merlin.4.3.2~4.13preview (available: false)
- [x] merlin.4.4.1~4.14preview (available: false)
- [x] merlin.4.6.1~5.0preview (available: false)

## ocaml source
- [x] ocaml-src.4.13.dev (flags: avoid-version)
- [x] ocaml-src.4.14.dev (flags: avoid-version)
- [x] ocaml-src.5.0.dev (flags: avoid-version)

## statmemprof (suggestion: add checksums)
note there's as well 4.04.2+statistical-memproif, and 4.06.1 - both with checksums
see https://github.com/ocaml/opam-repository/pull/25982
- [x] ocaml-variants.4.03.0+statistical-memprof (src: "https://github.com/jhjourdan/ocaml/archive/memprof_4.03.tar.gz")
- [x] ocaml-variants.4.05.0+statistical-memprof (src: "https://github.com/jhjourdan/ocaml/archive/memprof_4.05.0.tar.gz")
- [x] ocaml-variants.4.06.0+statistical-memprof (src: "https://github.com/jhjourdan/ocaml/archive/memprof_4.06.0.tar.gz")
- [x] ocaml-variants.4.07.1+statistical-memprof (src: "https://github.com/jhjourdan/ocaml/archive/memprof_4.07.1.tar.gz")

## variants (suggestion: keep them, but better not accept new ones without a tarball)
- [ ] ocaml-variants.4.10.0+nnpcheck (src: "git+https://github.com/kayceesrk/ocaml.git#4.10.0+nnp+check")
- [ ] ocaml-variants.4.12.0+domains (src: "git+https://github.com/ocaml-multicore/ocaml-multicore.git#4.12+domains")
- [ ] ocaml-variants.4.12.0+domains+effects (src: "git+https://github.com/ocaml-multicore/ocaml-multicore.git#4.12+domains+effects")
- [ ] ocaml-variants.5.0.0+tsan (src: "https://github.com/ocaml-multicore/ocaml-tsan/archive/5.0.0+tsan.tar.gz")
- [ ] ocaml-variants.4.02.3+buckle-master (src: "https://github.com/bloomberg/ocaml/archive/master.zip")

## variants + trunk
- [x] ocaml-variants.4.02.4+trunk
- [x] ocaml-variants.4.03.1+trunk
- [x] ocaml-variants.4.04.3+trunk
- [x] ocaml-variants.4.05.1+trunk
- [x] ocaml-variants.4.05.1+trunk+afl
- [x] ocaml-variants.4.05.1+trunk+flambda
- [x] ocaml-variants.4.05.1+trunk+fp
- [x] ocaml-variants.4.05.1+trunk+fp+flambda
- [x] ocaml-variants.4.05.1+trunk+safe-string
- [x] ocaml-variants.4.06.2+trunk
- [x] ocaml-variants.4.06.2+trunk+afl
- [x] ocaml-variants.4.06.2+trunk+flambda
- [x] ocaml-variants.4.06.2+trunk+force-safe-string
- [x] ocaml-variants.4.06.2+trunk+fp
- [x] ocaml-variants.4.06.2+trunk+fp+flambda
- [x] ocaml-variants.4.07.2+trunk
- [x] ocaml-variants.4.07.2+trunk+afl
- [x] ocaml-variants.4.07.2+trunk+default-unsafe-string
- [x] ocaml-variants.4.07.2+trunk+flambda
- [x] ocaml-variants.4.07.2+trunk+fp
- [x] ocaml-variants.4.07.2+trunk+fp+flambda
- [x] ocaml-variants.4.08.2+trunk
- [x] ocaml-variants.4.08.2+trunk+afl
- [x] ocaml-variants.4.08.2+trunk+default-unsafe-string
- [x] ocaml-variants.4.08.2+trunk+flambda
- [x] ocaml-variants.4.08.2+trunk+force-safe-string
- [x] ocaml-variants.4.08.2+trunk+fp
- [x] ocaml-variants.4.08.2+trunk+fp+flambda
- [x] ocaml-variants.4.09.2+trunk
- [x] ocaml-variants.4.09.2+trunk+afl
- [x] ocaml-variants.4.09.2+trunk+default-unsafe-string
- [x] ocaml-variants.4.09.2+trunk+flambda
- [x] ocaml-variants.4.09.2+trunk+fp
- [x] ocaml-variants.4.09.2+trunk+fp+flambda
- [x] ocaml-variants.4.10.3+trunk
- [x] ocaml-variants.4.10.3+trunk+afl
- [x] ocaml-variants.4.10.3+trunk+flambda
- [x] ocaml-variants.4.10.3+trunk+fp
- [x] ocaml-variants.4.11.3+trunk
- [x] ocaml-variants.4.11.3+trunk+afl
- [x] ocaml-variants.4.11.3+trunk+flambda
- [x] ocaml-variants.4.11.3+trunk+fp
- [x] ocaml-variants.4.12.2+trunk
- [x] ocaml-variants.4.13.2+trunk
- [x] ocaml-variants.4.14.3+trunk
- [x] ocaml-variants.5.0.1+trunk
- [x] ocaml-variants.5.1.2+trunk
- [x] ocaml-variants.5.2.1+trunk
- [x] ocaml-variants.5.3.0+trunk

**Comment by mseri** [comment]
For merlin preview and the arbitrary packages I would go with `available:false`.
In the first case this is what we did with all other preview packages

**Comment by hannesm** [comment]
updated the list above, and put links to the PRs that were merged. closing since I don't think there'll be anything for the compilers.
